//////////////////////////////////////////////////////////////////////////////
///   Copyright 2003 and onward LASMEA UMR 6602 CNRS/U.B.P Clermont-Ferrand
///   Copyright 2009 and onward LRI    UMR 8623 CNRS/Univ Paris Sud XI
///
///          Distributed under the Boost Software License, Version 1.0
///                 See accompanying file LICENSE.txt or copy at
///                     http://www.boost.org/LICENSE_1_0.txt
//////////////////////////////////////////////////////////////////////////////
#ifndef NT2_TOOLBOX_$MODULE_NAME$_$MODULE_NAME$_HPP_INCLUDED
#define NT2_TOOLBOX_$MODULE_NAME$_$MODULE_NAME$_HPP_INCLUDED

//<include> please don't modify between these tags
#include <nnt2/toolbox/r_mathlib/include/functions/pwilcox.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/pnbeta.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/tetragamma.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/dnorm.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/ptukey.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/lgammafn.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/bessel_i_ex.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/rnbinom_mu.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/rlogis.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/rnchisq.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/qtukey.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/beta.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/fprec.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/qnbinom_mu.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/pexp.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/pnbinom_mu.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/psigamma.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/dunif.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/pnchisq.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/log1pmx.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/pythag.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/qchisq.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/dnchisq.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/pchisq.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/dweibull.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/rsignrank.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/qnchisq.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/qnbeta.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/dpois.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/log1p.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/lbeta.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/rgamma.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/bessel_i.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/bessel_j.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/dlogis.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/dbeta.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/logspace_add.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/qbinom.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/bessel_y.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/bessel_y_ex.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/pnf.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/punif.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/norm_rand.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/qunif.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/fmax2.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/pnorm.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/pnt.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/lgamma1p.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/dgeom.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/rweibull.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/qlnorm.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/pf.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/dnt.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/gammafn.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/rnbeta.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/pt.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/dnf.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/fsign.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/pgeom.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/unif_rand.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/dwilcox.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/bessel_j_ex.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/qnorm.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/digamma.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/ppois.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/qwilcox.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/dlnorm.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/qgeom.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/pbeta.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/expm1.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/dsignrank.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/plogis.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/qcauchy.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/qnf.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/lchoose.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/pgamma.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/qpois.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/psignrank.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/qlogis.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/pweibull.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/rchisq.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/fround.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/rwilcox.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/qbeta.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/pentagamma.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/bessel_k.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/rt.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/rhyper.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/dexp.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/logspace_sub.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/ftrunc.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/hypot.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/sign.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/qnt.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/rcauchy.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/qf.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/dcauchy.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/dchisq.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/bessel_k_ex.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/pnbinom.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/pbinom.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/qt.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/qhyper.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/qweibull.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/dbinom.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/dt.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/rexp.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/qsignrank.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/rgeom.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/qgamma.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/exp_rand.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/rpois.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/df.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/fmin2.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/lgammafn_sign.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/rnbinom.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/qexp.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/rbeta.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/choose.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/trigamma.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/phyper.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/rf.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/qnbinom.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/dnbeta.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/pcauchy.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/rbinom.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/rnorm.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/dnbinom_mu.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/dgamma.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/plnorm.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/runif.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/rlnorm.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/dnbinom.hpp>
#include <nnt2/toolbox/r_mathlib/include/functions/dhyper.hpp>
//<\include>

#endif
